const mongoose = require('mongoose');

const Application2Schema = new mongoose.Schema ({
    job2Id : {
        type : mongoose.Schema.Types.ObjectId,
        ref : 'Job2',
        required : true
    },
    candidateName: {
        type: String,
        required: [true, 'Candidate name is required'],
        trim: true,
    },
    email: {
        type: String,
        required: [true, 'Email is required'],
        trim: true,
        lowercase: true,
    },
    aiSummary: {
        type: String, // The bullet points generated by the AI
        default: '',
    },
    aiScore: {
        type: Number, // A fit score out of 100 generated by the AI
        min: 0,
        max: 100,
        default: 0,
    }
},{timestamps : true});

module.exports = mongoose.model('Application2', Application2Schema);